apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::240702057348:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-SHK2XJ599FJ7
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::240702057348:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-29T05:51:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1544"
  uid: 7ab27ca3-8302-4539-9031-2181f667e095
